on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - main
name: 🚀 Deploy to Prod!
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🔨 Build Docker App
        run: |
          curl -f -X POST https://web2py.lalwut.com/githooks/app/azgen_api -H 'Content-Type: application/json' -d '{"TOKEN":"${{ secrets.DEPLOY_TOKEN }}"}'
